name: apphoctienganh
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  firebase_ui_auth: ^1.16.1
  provider: ^6.1.4
  google_sign_in: ^6.3.0
  flutter_facebook_auth: ^7.1.1
  font_awesome_flutter: ^10.8.0
  uuid: ^4.5.1
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_gemini: ^3.0.0
  dash_chat_2: ^0.0.21
  go_router: ^15.0.0
  flip_card: ^0.7.0
  flutter_tts: ^4.2.2
  rflutter_alert: ^2.0.7
  cloud_firestore: ^5.6.6
  awesome_snackbar_content: ^0.1.5
  carousel_slider: ^5.0.0
  gif: ^2.3.0
  connectivity_plus: ^6.1.4
  http: ^1.3.0
  firebase_messaging: ^15.2.5
  permission_handler: ^12.0.0+1
  speech_to_text: ^7.0.0
  shared_preferences: ^2.5.3

 

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logoapp.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0


# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    

  